/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;

import com.example.*;
import com.example.models.*;
import com.example.exceptions.*;
import com.example.http.client.HttpClient;
import com.example.http.client.HttpContext;
import com.example.http.request.HttpRequest;
import com.example.http.response.HttpResponse;
import com.example.http.response.HttpStringResponse;
import com.example.http.client.APICallBack;
import com.example.controllers.syncwrapper.APICallBackCatcher;

public class CallbacksController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static CallbacksController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the CallbacksController class 
     */
    public static CallbacksController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new CallbacksController();
            }
        }
        return instance;
    }

    /**
     * Stops the platform from sending callback messages for the specified account and service.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @param    sname    Required parameter: Service name
     * @return    Returns the CallbackActionResponse response from the API call 
     */
    public CallbackActionResponse deleteUnregisterCallbackUsingDELETE(
                final String vZM2MToken,
                final String aname,
                final String sname
    ) throws Throwable {
        APICallBackCatcher<CallbackActionResponse> callback = new APICallBackCatcher<CallbackActionResponse>();
        deleteUnregisterCallbackUsingDELETEAsync(vZM2MToken, aname, sname, callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Stops the platform from sending callback messages for the specified account and service.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @param    sname    Required parameter: Service name
     * @return    Returns the void response from the API call 
     */
    public void deleteUnregisterCallbackUsingDELETEAsync(
                final String vZM2MToken,
                final String aname,
                final String sname,
                final APICallBack<CallbackActionResponse> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/callbacks/{aname}/name/{sname}");

        //process template parameters
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 5345600620066210511L;
            {
                    put( "aname", aname );
                    put( "sname", sname );
            }});
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5338465497063538163L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "VZ-M2M-Token", vZM2MToken );
                    put( "api_key", Configuration.apiKey );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().delete(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //Error handling using HTTP status codes
                            int _responseCode = _response.getStatusCode();
                            if (_responseCode == 400)
                                throw new RestErrorResponseException("Error Response", _context);

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            CallbackActionResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<CallbackActionResponse>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Registers a URL where an account will receive RESTFul messages from a platform callback service.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @param    request    Required parameter: Request
     * @return    Returns the CallbackActionResponse response from the API call 
     */
    public CallbackActionResponse createRegisterCallbackUsingPOST(
                final String vZM2MToken,
                final String aname,
                final RegisterCallbackRequest request
    ) throws Throwable {
        APICallBackCatcher<CallbackActionResponse> callback = new APICallBackCatcher<CallbackActionResponse>();
        createRegisterCallbackUsingPOSTAsync(vZM2MToken, aname, request, callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Registers a URL where an account will receive RESTFul messages from a platform callback service.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @param    request    Required parameter: Request
     * @return    Returns the void response from the API call 
     */
    public void createRegisterCallbackUsingPOSTAsync(
                final String vZM2MToken,
                final String aname,
                final RegisterCallbackRequest request,
                final APICallBack<CallbackActionResponse> callBack
    ) throws JsonProcessingException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/callbacks/{aname}");

        //process template parameters
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 5016655138473478091L;
            {
                    put( "aname", aname );
            }});
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5696202347504091106L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "VZ-M2M-Token", vZM2MToken );
                    put( "api_key", Configuration.apiKey );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().postBody(_queryUrl, _headers, APIHelper.serialize(request));

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //Error handling using HTTP status codes
                            int _responseCode = _response.getStatusCode();
                            if (_responseCode == 400)
                                throw new RestErrorResponseException("Error Response", _context);

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            CallbackActionResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<CallbackActionResponse>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Returns the name and endpoint URL of all callback listening services registered for a given account.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @return    Returns the List<Callback> response from the API call 
     */
    public List<Callback> listCallbacksUsingGET(
                final String vZM2MToken,
                final String aname
    ) throws Throwable {
        APICallBackCatcher<List<Callback>> callback = new APICallBackCatcher<List<Callback>>();
        listCallbacksUsingGETAsync(vZM2MToken, aname, callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Returns the name and endpoint URL of all callback listening services registered for a given account.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @return    Returns the void response from the API call 
     */
    public void listCallbacksUsingGETAsync(
                final String vZM2MToken,
                final String aname,
                final APICallBack<List<Callback>> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/callbacks/{aname}");

        //process template parameters
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 5199310403290769870L;
            {
                    put( "aname", aname );
            }});
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 4797006901806302924L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "VZ-M2M-Token", vZM2MToken );
                    put( "api_key", Configuration.apiKey );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //Error handling using HTTP status codes
                            int _responseCode = _response.getStatusCode();
                            if (_responseCode == 400)
                                throw new RestErrorResponseException("Error Response", _context);

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            List<Callback> _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<List<Callback>>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}