/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import com.example.*;
import com.example.models.*;
import com.example.exceptions.*;
import com.example.http.client.HttpClient;
import com.example.http.client.HttpContext;
import com.example.http.request.HttpRequest;
import com.example.http.response.HttpResponse;
import com.example.http.response.HttpStringResponse;
import com.example.http.client.APICallBack;
import com.example.controllers.syncwrapper.APICallBackCatcher;

public class PlansController extends BaseController {    
    //private static variables for the singleton pattern
    private static Object syncObject = new Object();
    private static PlansController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the PlansController class 
     */
    public static PlansController getInstance() {
        synchronized (syncObject) {
            if (null == instance) {
                instance = new PlansController();
            }
        }
        return instance;
    }

    /**
     * Returns a list of all data service plans that are associated with a specified account.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @return    Returns the List<ServicePlanResponse> response from the API call 
     */
    public List<ServicePlanResponse> getServicePlanListUsingGET(
                final String vZM2MToken,
                final String aname
    ) throws Throwable {
        APICallBackCatcher<List<ServicePlanResponse>> callback = new APICallBackCatcher<List<ServicePlanResponse>>();
        getServicePlanListUsingGETAsync(vZM2MToken, aname, callback);
        if(!callback.isSuccess())
            throw callback.getError();
        return callback.getResult();
    }

    /**
     * Returns a list of all data service plans that are associated with a specified account.
     * @param    vZM2MToken    Required parameter: M2M-MC Session Token
     * @param    aname    Required parameter: Account name
     * @return    Returns the void response from the API call 
     */
    public void getServicePlanListUsingGETAsync(
                final String vZM2MToken,
                final String aname,
                final APICallBack<List<ServicePlanResponse>> callBack
    ) {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri);
        _queryBuilder.append("/plans/{aname}");

        //process template parameters
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, new HashMap<String, Object>() {
            private static final long serialVersionUID = 4964751719099664118L;
            {
                    put( "aname", aname );
            }});
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>() {
            private static final long serialVersionUID = 5633916628294433277L;
            {
                    put( "user-agent", "APIMATIC 2.0" );
                    put( "accept", "application/json" );
                    put( "VZ-M2M-Token", vZM2MToken );
                    put( "api_key", Configuration.apiKey );
            }
        };

        //prepare and invoke the API call request to fetch the response
        final HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        //invoke the callback before request if its not null
        if (getHttpCallBack() != null)
        {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        //invoke request and get response
        Runnable _responseTask = new Runnable() {
            public void run() {
                //make the API call
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {

                            //invoke the callback after response if its not null
                            if (getHttpCallBack() != null)	
                            {
                                getHttpCallBack().OnAfterResponse(_context);
                            }

                            //Error handling using HTTP status codes
                            int _responseCode = _response.getStatusCode();
                            if (_responseCode == 400)
                                throw new RestErrorResponseException("Error Response", _context);

                            //handle errors defined at the API level
                            validateResponse(_response, _context);

                            //extract result from the http response
                            String _responseBody = ((HttpStringResponse)_response).getBody();
                            List<ServicePlanResponse> _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<List<ServicePlanResponse>>(){});

                            //let the caller know of the success
                            callBack.onSuccess(_context, _result);
                        } catch (APIException error) {
                            //let the caller know of the error
                            callBack.onFailure(_context, error);
                        } catch (IOException ioException) {
                            //let the caller know of the caught IO Exception
                            callBack.onFailure(_context, ioException);
                        } catch (Exception exception) {
                            //let the caller know of the caught Exception
                            callBack.onFailure(_context, exception);
                        }
                    }
                    public void onFailure(HttpContext _context, Throwable _error) {
                        //invoke the callback after response if its not null
                        if (getHttpCallBack() != null)	
                            {
                            getHttpCallBack().OnAfterResponse(_context);
                        }

                        //let the caller know of the failure
                        callBack.onFailure(_context, _error);
                    }
                });
            }
        };

        //execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

}