/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class AddDevicesRequestBuilder {
    //the instance to build
    private AddDevicesRequest addDevicesRequest;

    /**
     * Default constructor to initialize the instance
     */
    public AddDevicesRequestBuilder() {
        addDevicesRequest = new AddDevicesRequest();
    }

    public AddDevicesRequestBuilder accountName(String accountName) {
        addDevicesRequest.setAccountName(accountName);
        return this;
    }

    public AddDevicesRequestBuilder customFields(List<KvPair> customFields) {
        addDevicesRequest.setCustomFields(customFields);
        return this;
    }

    public AddDevicesRequestBuilder devicesToAdd(List<DeviceList> devicesToAdd) {
        addDevicesRequest.setDevicesToAdd(devicesToAdd);
        return this;
    }

    public AddDevicesRequestBuilder groupName(String groupName) {
        addDevicesRequest.setGroupName(groupName);
        return this;
    }

    public AddDevicesRequestBuilder skuNumber(String skuNumber) {
        addDevicesRequest.setSkuNumber(skuNumber);
        return this;
    }

    public AddDevicesRequestBuilder state(String state) {
        addDevicesRequest.setState(state);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AddDevicesRequest build() {
        return addDevicesRequest;
    }
}