/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AddDevicesRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5705971409839827452L;
    private String accountName;
    private List<KvPair> customFields;
    private List<DeviceList> devicesToAdd;
    private String groupName;
    private String skuNumber;
    private String state;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customFields")
    public List<KvPair> getCustomFields ( ) { 
        return this.customFields;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customFields")
    public void setCustomFields (List<KvPair> value) { 
        this.customFields = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devicesToAdd")
    public List<DeviceList> getDevicesToAdd ( ) { 
        return this.devicesToAdd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devicesToAdd")
    public void setDevicesToAdd (List<DeviceList> value) { 
        this.devicesToAdd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("skuNumber")
    public String getSkuNumber ( ) { 
        return this.skuNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("skuNumber")
    public void setSkuNumber (String value) { 
        this.skuNumber = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("state")
    public String getState ( ) { 
        return this.state;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("state")
    public void setState (String value) { 
        this.state = value;
    }
 
}
 