/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class AddDevicesResponseMessage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5700110164443930769L;
    private List<DeviceId> deviceIds;
    private String response;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceIds")
    public List<DeviceId> getDeviceIds ( ) { 
        return this.deviceIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds (List<DeviceId> value) { 
        this.deviceIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("response")
    public String getResponse ( ) { 
        return this.response;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("response")
    public void setResponse (String value) { 
        this.response = value;
    }
 
}
 