/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CallbackActionResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4953487320389362873L;
    private String accountName;
    private String serviceName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("serviceName")
    public String getServiceName ( ) { 
        return this.serviceName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("serviceName")
    public void setServiceName (String value) { 
        this.serviceName = value;
    }
 
}
 