/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CallbackActionResponseBuilder {
    //the instance to build
    private CallbackActionResponse callbackActionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public CallbackActionResponseBuilder() {
        callbackActionResponse = new CallbackActionResponse();
    }

    public CallbackActionResponseBuilder accountName(String accountName) {
        callbackActionResponse.setAccountName(accountName);
        return this;
    }

    public CallbackActionResponseBuilder serviceName(String serviceName) {
        callbackActionResponse.setServiceName(serviceName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CallbackActionResponse build() {
        return callbackActionResponse;
    }
}