/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CallbackBuilder {
    //the instance to build
    private Callback callback;

    /**
     * Default constructor to initialize the instance
     */
    public CallbackBuilder() {
        callback = new Callback();
    }

    public CallbackBuilder accountName(String accountName) {
        callback.setAccountName(accountName);
        return this;
    }

    public CallbackBuilder password(String password) {
        callback.setPassword(password);
        return this;
    }

    public CallbackBuilder serviceName(String serviceName) {
        callback.setServiceName(serviceName);
        return this;
    }

    public CallbackBuilder url(String url) {
        callback.setUrl(url);
        return this;
    }

    public CallbackBuilder username(String username) {
        callback.setUsername(username);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Callback build() {
        return callback;
    }
}