/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CarrierActivateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5667627019323356329L;
    private String accountName;
    private String carrierIpPoolName;
    private String carrierName;
    private String costCenterCode;
    private List<KvPair> customFields;
    private List<DeviceList> devices;
    private String groupName;
    private String leadId;
    private String mdnZipCode;
    private PlaceOfUse primaryPlaceOfUse;
    private String publicIpRestriction;
    private String servicePlan;
    private String skuNumber;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("carrierIpPoolName")
    public String getCarrierIpPoolName ( ) { 
        return this.carrierIpPoolName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("carrierIpPoolName")
    public void setCarrierIpPoolName (String value) { 
        this.carrierIpPoolName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("carrierName")
    public String getCarrierName ( ) { 
        return this.carrierName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("carrierName")
    public void setCarrierName (String value) { 
        this.carrierName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("costCenterCode")
    public String getCostCenterCode ( ) { 
        return this.costCenterCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("costCenterCode")
    public void setCostCenterCode (String value) { 
        this.costCenterCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customFields")
    public List<KvPair> getCustomFields ( ) { 
        return this.customFields;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customFields")
    public void setCustomFields (List<KvPair> value) { 
        this.customFields = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devices")
    public List<DeviceList> getDevices ( ) { 
        return this.devices;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devices")
    public void setDevices (List<DeviceList> value) { 
        this.devices = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leadId")
    public String getLeadId ( ) { 
        return this.leadId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leadId")
    public void setLeadId (String value) { 
        this.leadId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mdnZipCode")
    public String getMdnZipCode ( ) { 
        return this.mdnZipCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mdnZipCode")
    public void setMdnZipCode (String value) { 
        this.mdnZipCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("primaryPlaceOfUse")
    public PlaceOfUse getPrimaryPlaceOfUse ( ) { 
        return this.primaryPlaceOfUse;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("primaryPlaceOfUse")
    public void setPrimaryPlaceOfUse (PlaceOfUse value) { 
        this.primaryPlaceOfUse = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("publicIpRestriction")
    public String getPublicIpRestriction ( ) { 
        return this.publicIpRestriction;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("publicIpRestriction")
    public void setPublicIpRestriction (String value) { 
        this.publicIpRestriction = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("skuNumber")
    public String getSkuNumber ( ) { 
        return this.skuNumber;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("skuNumber")
    public void setSkuNumber (String value) { 
        this.skuNumber = value;
    }
 
}
 