/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CarrierInformation 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4757901526467261362L;
    private String carrierName;
    private String servicePlan;
    private String state;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("carrierName")
    public String getCarrierName ( ) { 
        return this.carrierName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("carrierName")
    public void setCarrierName (String value) { 
        this.carrierName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("state")
    public String getState ( ) { 
        return this.state;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("state")
    public void setState (String value) { 
        this.state = value;
    }
 
}
 