/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CarrierDeactivateRequestBuilder {
    //the instance to build
    private CarrierDeactivateRequest carrierDeactivateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CarrierDeactivateRequestBuilder() {
        carrierDeactivateRequest = new CarrierDeactivateRequest();
    }

    public CarrierDeactivateRequestBuilder accountName(String accountName) {
        carrierDeactivateRequest.setAccountName(accountName);
        return this;
    }

    public CarrierDeactivateRequestBuilder customFields(List<KvPair> customFields) {
        carrierDeactivateRequest.setCustomFields(customFields);
        return this;
    }

    public CarrierDeactivateRequestBuilder devices(List<DeviceList> devices) {
        carrierDeactivateRequest.setDevices(devices);
        return this;
    }

    public CarrierDeactivateRequestBuilder etfWaiver(Boolean etfWaiver) {
        carrierDeactivateRequest.setEtfWaiver(etfWaiver);
        return this;
    }

    public CarrierDeactivateRequestBuilder groupName(String groupName) {
        carrierDeactivateRequest.setGroupName(groupName);
        return this;
    }

    public CarrierDeactivateRequestBuilder reasonCode(String reasonCode) {
        carrierDeactivateRequest.setReasonCode(reasonCode);
        return this;
    }

    public CarrierDeactivateRequestBuilder servicePlan(String servicePlan) {
        carrierDeactivateRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CarrierDeactivateRequest build() {
        return carrierDeactivateRequest;
    }
}