/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CarrierActivateRequestBuilder {
    //the instance to build
    private CarrierActivateRequest carrierActivateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CarrierActivateRequestBuilder() {
        carrierActivateRequest = new CarrierActivateRequest();
    }

    public CarrierActivateRequestBuilder accountName(String accountName) {
        carrierActivateRequest.setAccountName(accountName);
        return this;
    }

    public CarrierActivateRequestBuilder carrierIpPoolName(String carrierIpPoolName) {
        carrierActivateRequest.setCarrierIpPoolName(carrierIpPoolName);
        return this;
    }

    public CarrierActivateRequestBuilder carrierName(String carrierName) {
        carrierActivateRequest.setCarrierName(carrierName);
        return this;
    }

    public CarrierActivateRequestBuilder costCenterCode(String costCenterCode) {
        carrierActivateRequest.setCostCenterCode(costCenterCode);
        return this;
    }

    public CarrierActivateRequestBuilder customFields(List<KvPair> customFields) {
        carrierActivateRequest.setCustomFields(customFields);
        return this;
    }

    public CarrierActivateRequestBuilder devices(List<DeviceList> devices) {
        carrierActivateRequest.setDevices(devices);
        return this;
    }

    public CarrierActivateRequestBuilder groupName(String groupName) {
        carrierActivateRequest.setGroupName(groupName);
        return this;
    }

    public CarrierActivateRequestBuilder leadId(String leadId) {
        carrierActivateRequest.setLeadId(leadId);
        return this;
    }

    public CarrierActivateRequestBuilder mdnZipCode(String mdnZipCode) {
        carrierActivateRequest.setMdnZipCode(mdnZipCode);
        return this;
    }

    public CarrierActivateRequestBuilder primaryPlaceOfUse(PlaceOfUse primaryPlaceOfUse) {
        carrierActivateRequest.setPrimaryPlaceOfUse(primaryPlaceOfUse);
        return this;
    }

    public CarrierActivateRequestBuilder publicIpRestriction(String publicIpRestriction) {
        carrierActivateRequest.setPublicIpRestriction(publicIpRestriction);
        return this;
    }

    public CarrierActivateRequestBuilder servicePlan(String servicePlan) {
        carrierActivateRequest.setServicePlan(servicePlan);
        return this;
    }

    public CarrierActivateRequestBuilder skuNumber(String skuNumber) {
        carrierActivateRequest.setSkuNumber(skuNumber);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CarrierActivateRequest build() {
        return carrierActivateRequest;
    }
}