/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CarrierActionsRequestBuilder {
    //the instance to build
    private CarrierActionsRequest carrierActionsRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CarrierActionsRequestBuilder() {
        carrierActionsRequest = new CarrierActionsRequest();
    }

    public CarrierActionsRequestBuilder accountName(String accountName) {
        carrierActionsRequest.setAccountName(accountName);
        return this;
    }

    public CarrierActionsRequestBuilder customFields(List<KvPair> customFields) {
        carrierActionsRequest.setCustomFields(customFields);
        return this;
    }

    public CarrierActionsRequestBuilder devices(List<DeviceList> devices) {
        carrierActionsRequest.setDevices(devices);
        return this;
    }

    public CarrierActionsRequestBuilder groupName(String groupName) {
        carrierActionsRequest.setGroupName(groupName);
        return this;
    }

    public CarrierActionsRequestBuilder servicePlan(String servicePlan) {
        carrierActionsRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CarrierActionsRequest build() {
        return carrierActionsRequest;
    }
}