/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CarrierInformationBuilder {
    //the instance to build
    private CarrierInformation carrierInformation;

    /**
     * Default constructor to initialize the instance
     */
    public CarrierInformationBuilder() {
        carrierInformation = new CarrierInformation();
    }

    public CarrierInformationBuilder carrierName(String carrierName) {
        carrierInformation.setCarrierName(carrierName);
        return this;
    }

    public CarrierInformationBuilder servicePlan(String servicePlan) {
        carrierInformation.setServicePlan(servicePlan);
        return this;
    }

    public CarrierInformationBuilder state(String state) {
        carrierInformation.setState(state);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CarrierInformation build() {
        return carrierInformation;
    }
}