/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ChangeDeviceIdRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4675369616676731169L;
    private Boolean assignNonGeoMdn;
    private String change4gOption;
    private List<DeviceId> deviceIds;
    private List<DeviceId> deviceIdsTo;
    private String npaNxx;
    private String servicePlan;
    private String zipCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("assignNonGeoMdn")
    public Boolean getAssignNonGeoMdn ( ) { 
        return this.assignNonGeoMdn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("assignNonGeoMdn")
    public void setAssignNonGeoMdn (Boolean value) { 
        this.assignNonGeoMdn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("change4gOption")
    public String getChange4gOption ( ) { 
        return this.change4gOption;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("change4gOption")
    public void setChange4gOption (String value) { 
        this.change4gOption = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceIds")
    public List<DeviceId> getDeviceIds ( ) { 
        return this.deviceIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds (List<DeviceId> value) { 
        this.deviceIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceIdsTo")
    public List<DeviceId> getDeviceIdsTo ( ) { 
        return this.deviceIdsTo;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceIdsTo")
    public void setDeviceIdsTo (List<DeviceId> value) { 
        this.deviceIdsTo = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("npaNxx")
    public String getNpaNxx ( ) { 
        return this.npaNxx;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("npaNxx")
    public void setNpaNxx (String value) { 
        this.npaNxx = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("zipCode")
    public String getZipCode ( ) { 
        return this.zipCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("zipCode")
    public void setZipCode (String value) { 
        this.zipCode = value;
    }
 
}
 