/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ChangeDeviceIdRequestBuilder {
    //the instance to build
    private ChangeDeviceIdRequest changeDeviceIdRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ChangeDeviceIdRequestBuilder() {
        changeDeviceIdRequest = new ChangeDeviceIdRequest();
    }

    public ChangeDeviceIdRequestBuilder assignNonGeoMdn(Boolean assignNonGeoMdn) {
        changeDeviceIdRequest.setAssignNonGeoMdn(assignNonGeoMdn);
        return this;
    }

    public ChangeDeviceIdRequestBuilder change4gOption(String change4gOption) {
        changeDeviceIdRequest.setChange4gOption(change4gOption);
        return this;
    }

    public ChangeDeviceIdRequestBuilder deviceIds(List<DeviceId> deviceIds) {
        changeDeviceIdRequest.setDeviceIds(deviceIds);
        return this;
    }

    public ChangeDeviceIdRequestBuilder deviceIdsTo(List<DeviceId> deviceIdsTo) {
        changeDeviceIdRequest.setDeviceIdsTo(deviceIdsTo);
        return this;
    }

    public ChangeDeviceIdRequestBuilder npaNxx(String npaNxx) {
        changeDeviceIdRequest.setNpaNxx(npaNxx);
        return this;
    }

    public ChangeDeviceIdRequestBuilder servicePlan(String servicePlan) {
        changeDeviceIdRequest.setServicePlan(servicePlan);
        return this;
    }

    public ChangeDeviceIdRequestBuilder zipCode(String zipCode) {
        changeDeviceIdRequest.setZipCode(zipCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ChangeDeviceIdRequest build() {
        return changeDeviceIdRequest;
    }
}