/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConnectionEvent 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5168683089070498771L;
    private List<KvPair> connectionEventAttributes;
    private List<KvPair> extendedAttributes;
    private String occurredAt;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("connectionEventAttributes")
    public List<KvPair> getConnectionEventAttributes ( ) { 
        return this.connectionEventAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("connectionEventAttributes")
    public void setConnectionEventAttributes (List<KvPair> value) { 
        this.connectionEventAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extendedAttributes")
    public List<KvPair> getExtendedAttributes ( ) { 
        return this.extendedAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes (List<KvPair> value) { 
        this.extendedAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("occurredAt")
    public String getOccurredAt ( ) { 
        return this.occurredAt;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("occurredAt")
    public void setOccurredAt (String value) { 
        this.occurredAt = value;
    }
 
}
 