/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ConnectionEventBuilder {
    //the instance to build
    private ConnectionEvent connectionEvent;

    /**
     * Default constructor to initialize the instance
     */
    public ConnectionEventBuilder() {
        connectionEvent = new ConnectionEvent();
    }

    public ConnectionEventBuilder connectionEventAttributes(List<KvPair> connectionEventAttributes) {
        connectionEvent.setConnectionEventAttributes(connectionEventAttributes);
        return this;
    }

    public ConnectionEventBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        connectionEvent.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public ConnectionEventBuilder occurredAt(String occurredAt) {
        connectionEvent.setOccurredAt(occurredAt);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConnectionEvent build() {
        return connectionEvent;
    }
}