/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ConnectionHistoryResponseBuilder {
    //the instance to build
    private ConnectionHistoryResponse connectionHistoryResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ConnectionHistoryResponseBuilder() {
        connectionHistoryResponse = new ConnectionHistoryResponse();
    }

    public ConnectionHistoryResponseBuilder connectionHistory(List<ConnectionEvent> connectionHistory) {
        connectionHistoryResponse.setConnectionHistory(connectionHistory);
        return this;
    }

    public ConnectionHistoryResponseBuilder hasMoreData(Boolean hasMoreData) {
        connectionHistoryResponse.setHasMoreData(hasMoreData);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ConnectionHistoryResponse build() {
        return connectionHistoryResponse;
    }
}