/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ConnectionHistoryResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4904610810193755420L;
    private List<ConnectionEvent> connectionHistory;
    private Boolean hasMoreData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("connectionHistory")
    public List<ConnectionEvent> getConnectionHistory ( ) { 
        return this.connectionHistory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("connectionHistory")
    public void setConnectionHistory (List<ConnectionEvent> value) { 
        this.connectionHistory = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
}
 