/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CreateDevGroupRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4813449343815302392L;
    private String accountName;
    private List<DeviceId> devicesToAdd;
    private String groupDescription;
    private String groupName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devicesToAdd")
    public List<DeviceId> getDevicesToAdd ( ) { 
        return this.devicesToAdd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devicesToAdd")
    public void setDevicesToAdd (List<DeviceId> value) { 
        this.devicesToAdd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupDescription")
    public String getGroupDescription ( ) { 
        return this.groupDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupDescription")
    public void setGroupDescription (String value) { 
        this.groupDescription = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
}
 