/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CreateDevGroupRequestBuilder {
    //the instance to build
    private CreateDevGroupRequest createDevGroupRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateDevGroupRequestBuilder() {
        createDevGroupRequest = new CreateDevGroupRequest();
    }

    public CreateDevGroupRequestBuilder accountName(String accountName) {
        createDevGroupRequest.setAccountName(accountName);
        return this;
    }

    public CreateDevGroupRequestBuilder devicesToAdd(List<DeviceId> devicesToAdd) {
        createDevGroupRequest.setDevicesToAdd(devicesToAdd);
        return this;
    }

    public CreateDevGroupRequestBuilder groupDescription(String groupDescription) {
        createDevGroupRequest.setGroupDescription(groupDescription);
        return this;
    }

    public CreateDevGroupRequestBuilder groupName(String groupName) {
        createDevGroupRequest.setGroupName(groupName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateDevGroupRequest build() {
        return createDevGroupRequest;
    }
}