/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CustomerName 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5339549261119036843L;
    private String firstName;
    private String lastName;
    private String middleName;
    private String title;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("firstName")
    public String getFirstName ( ) { 
        return this.firstName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("firstName")
    public void setFirstName (String value) { 
        this.firstName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastName")
    public String getLastName ( ) { 
        return this.lastName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastName")
    public void setLastName (String value) { 
        this.lastName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("middleName")
    public String getMiddleName ( ) { 
        return this.middleName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("middleName")
    public void setMiddleName (String value) { 
        this.middleName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("title")
    public String getTitle ( ) { 
        return this.title;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("title")
    public void setTitle (String value) { 
        this.title = value;
    }
 
}
 