/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class CustomFieldsUpdateRequestBuilder {
    //the instance to build
    private CustomFieldsUpdateRequest customFieldsUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CustomFieldsUpdateRequestBuilder() {
        customFieldsUpdateRequest = new CustomFieldsUpdateRequest();
    }

    public CustomFieldsUpdateRequestBuilder accountName(String accountName) {
        customFieldsUpdateRequest.setAccountName(accountName);
        return this;
    }

    public CustomFieldsUpdateRequestBuilder customFields(List<KvPair> customFields) {
        customFieldsUpdateRequest.setCustomFields(customFields);
        return this;
    }

    public CustomFieldsUpdateRequestBuilder customFieldsToUpdate(List<KvPair> customFieldsToUpdate) {
        customFieldsUpdateRequest.setCustomFieldsToUpdate(customFieldsToUpdate);
        return this;
    }

    public CustomFieldsUpdateRequestBuilder devices(List<DeviceList> devices) {
        customFieldsUpdateRequest.setDevices(devices);
        return this;
    }

    public CustomFieldsUpdateRequestBuilder groupName(String groupName) {
        customFieldsUpdateRequest.setGroupName(groupName);
        return this;
    }

    public CustomFieldsUpdateRequestBuilder servicePlan(String servicePlan) {
        customFieldsUpdateRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CustomFieldsUpdateRequest build() {
        return customFieldsUpdateRequest;
    }
}