/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceCostCenterRequestBuilder {
    //the instance to build
    private DeviceCostCenterRequest deviceCostCenterRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceCostCenterRequestBuilder() {
        deviceCostCenterRequest = new DeviceCostCenterRequest();
    }

    public DeviceCostCenterRequestBuilder accountName(String accountName) {
        deviceCostCenterRequest.setAccountName(accountName);
        return this;
    }

    public DeviceCostCenterRequestBuilder costCenter(String costCenter) {
        deviceCostCenterRequest.setCostCenter(costCenter);
        return this;
    }

    public DeviceCostCenterRequestBuilder customFields(List<KvPair> customFields) {
        deviceCostCenterRequest.setCustomFields(customFields);
        return this;
    }

    public DeviceCostCenterRequestBuilder devices(List<DeviceList> devices) {
        deviceCostCenterRequest.setDevices(devices);
        return this;
    }

    public DeviceCostCenterRequestBuilder groupName(String groupName) {
        deviceCostCenterRequest.setGroupName(groupName);
        return this;
    }

    public DeviceCostCenterRequestBuilder removeCostCenter(Boolean removeCostCenter) {
        deviceCostCenterRequest.setRemoveCostCenter(removeCostCenter);
        return this;
    }

    public DeviceCostCenterRequestBuilder servicePlan(String servicePlan) {
        deviceCostCenterRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceCostCenterRequest build() {
        return deviceCostCenterRequest;
    }
}