/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceListBuilder {
    //the instance to build
    private DeviceList deviceList;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceListBuilder() {
        deviceList = new DeviceList();
    }

    public DeviceListBuilder deviceIds(List<DeviceId> deviceIds) {
        deviceList.setDeviceIds(deviceIds);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceList build() {
        return deviceList;
    }
}