/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceProvisioningHistoryListRequestBuilder {
    //the instance to build
    private DeviceProvisioningHistoryListRequest deviceProvisioningHistoryListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceProvisioningHistoryListRequestBuilder() {
        deviceProvisioningHistoryListRequest = new DeviceProvisioningHistoryListRequest();
    }

    public DeviceProvisioningHistoryListRequestBuilder deviceId(DeviceId deviceId) {
        deviceProvisioningHistoryListRequest.setDeviceId(deviceId);
        return this;
    }

    public DeviceProvisioningHistoryListRequestBuilder earliest(String earliest) {
        deviceProvisioningHistoryListRequest.setEarliest(earliest);
        return this;
    }

    public DeviceProvisioningHistoryListRequestBuilder latest(String latest) {
        deviceProvisioningHistoryListRequest.setLatest(latest);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceProvisioningHistoryListRequest build() {
        return deviceProvisioningHistoryListRequest;
    }
}