/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceBuilder {
    //the instance to build
    private Device device;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceBuilder() {
        device = new Device();
    }

    public DeviceBuilder accountName(String accountName) {
        device.setAccountName(accountName);
        return this;
    }

    public DeviceBuilder billingCycleEndDate(String billingCycleEndDate) {
        device.setBillingCycleEndDate(billingCycleEndDate);
        return this;
    }

    public DeviceBuilder carrierInformations(List<CarrierInformation> carrierInformations) {
        device.setCarrierInformations(carrierInformations);
        return this;
    }

    public DeviceBuilder connected(Boolean connected) {
        device.setConnected(connected);
        return this;
    }

    public DeviceBuilder createdAt(String createdAt) {
        device.setCreatedAt(createdAt);
        return this;
    }

    public DeviceBuilder customFields(List<KvPair> customFields) {
        device.setCustomFields(customFields);
        return this;
    }

    public DeviceBuilder deviceIds(List<DeviceId> deviceIds) {
        device.setDeviceIds(deviceIds);
        return this;
    }

    public DeviceBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        device.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public DeviceBuilder groupNames(List<String> groupNames) {
        device.setGroupNames(groupNames);
        return this;
    }

    public DeviceBuilder ipAddress(String ipAddress) {
        device.setIpAddress(ipAddress);
        return this;
    }

    public DeviceBuilder lastActivationBy(String lastActivationBy) {
        device.setLastActivationBy(lastActivationBy);
        return this;
    }

    public DeviceBuilder lastActivationDate(String lastActivationDate) {
        device.setLastActivationDate(lastActivationDate);
        return this;
    }

    public DeviceBuilder lastConnectionDate(String lastConnectionDate) {
        device.setLastConnectionDate(lastConnectionDate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Device build() {
        return device;
    }
}