/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceIdBuilder {
    //the instance to build
    private DeviceId deviceId;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceIdBuilder() {
        deviceId = new DeviceId();
    }

    public DeviceIdBuilder id(String id) {
        deviceId.setId(id);
        return this;
    }

    public DeviceIdBuilder kind(String kind) {
        deviceId.setKind(kind);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceId build() {
        return deviceId;
    }
}