/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceListResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5637482025511141932L;
    private List<Device> devices;
    private Boolean hasMoreData;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devices")
    public List<Device> getDevices ( ) { 
        return this.devices;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devices")
    public void setDevices (List<Device> value) { 
        this.devices = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
}
 