/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceProvisioningHistoryListResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5466991033624904689L;
    private Boolean hasMoreData;
    private List<ProvisioningHistory> provisioningHistory;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("provisioningHistory")
    public List<ProvisioningHistory> getProvisioningHistory ( ) { 
        return this.provisioningHistory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("provisioningHistory")
    public void setProvisioningHistory (List<ProvisioningHistory> value) { 
        this.provisioningHistory = value;
    }
 
}
 