/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceListRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5304812285308762013L;
    private String accountName;
    private String currentState;
    private List<KvPair> customFields;
    private DeviceId deviceId;
    private String earliest;
    private String groupName;
    private String latest;
    private String servicePlan;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currentState")
    public String getCurrentState ( ) { 
        return this.currentState;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currentState")
    public void setCurrentState (String value) { 
        this.currentState = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customFields")
    public List<KvPair> getCustomFields ( ) { 
        return this.customFields;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customFields")
    public void setCustomFields (List<KvPair> value) { 
        this.customFields = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceId")
    public DeviceId getDeviceId ( ) { 
        return this.deviceId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceId")
    public void setDeviceId (DeviceId value) { 
        this.deviceId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("earliest")
    public String getEarliest ( ) { 
        return this.earliest;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("earliest")
    public void setEarliest (String value) { 
        this.earliest = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("latest")
    public String getLatest ( ) { 
        return this.latest;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("latest")
    public void setLatest (String value) { 
        this.latest = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
}
 