/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceAggregateUsageListRequestBuilder {
    //the instance to build
    private DeviceAggregateUsageListRequest deviceAggregateUsageListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceAggregateUsageListRequestBuilder() {
        deviceAggregateUsageListRequest = new DeviceAggregateUsageListRequest();
    }

    public DeviceAggregateUsageListRequestBuilder accountName(String accountName) {
        deviceAggregateUsageListRequest.setAccountName(accountName);
        return this;
    }

    public DeviceAggregateUsageListRequestBuilder deviceIds(List<DeviceId> deviceIds) {
        deviceAggregateUsageListRequest.setDeviceIds(deviceIds);
        return this;
    }

    public DeviceAggregateUsageListRequestBuilder endTime(String endTime) {
        deviceAggregateUsageListRequest.setEndTime(endTime);
        return this;
    }

    public DeviceAggregateUsageListRequestBuilder groupName(String groupName) {
        deviceAggregateUsageListRequest.setGroupName(groupName);
        return this;
    }

    public DeviceAggregateUsageListRequestBuilder startTime(String startTime) {
        deviceAggregateUsageListRequest.setStartTime(startTime);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceAggregateUsageListRequest build() {
        return deviceAggregateUsageListRequest;
    }
}