/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceUsageListResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5532288117391676127L;
    private Boolean hasMoreData;
    private List<Usage> usageHistory;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("usageHistory")
    public List<Usage> getUsageHistory ( ) { 
        return this.usageHistory;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("usageHistory")
    public void setUsageHistory (List<Usage> value) { 
        this.usageHistory = value;
    }
 
}
 