/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceListRequestBuilder {
    //the instance to build
    private DeviceListRequest deviceListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceListRequestBuilder() {
        deviceListRequest = new DeviceListRequest();
    }

    public DeviceListRequestBuilder accountName(String accountName) {
        deviceListRequest.setAccountName(accountName);
        return this;
    }

    public DeviceListRequestBuilder currentState(String currentState) {
        deviceListRequest.setCurrentState(currentState);
        return this;
    }

    public DeviceListRequestBuilder customFields(List<KvPair> customFields) {
        deviceListRequest.setCustomFields(customFields);
        return this;
    }

    public DeviceListRequestBuilder deviceId(DeviceId deviceId) {
        deviceListRequest.setDeviceId(deviceId);
        return this;
    }

    public DeviceListRequestBuilder earliest(String earliest) {
        deviceListRequest.setEarliest(earliest);
        return this;
    }

    public DeviceListRequestBuilder groupName(String groupName) {
        deviceListRequest.setGroupName(groupName);
        return this;
    }

    public DeviceListRequestBuilder latest(String latest) {
        deviceListRequest.setLatest(latest);
        return this;
    }

    public DeviceListRequestBuilder servicePlan(String servicePlan) {
        deviceListRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceListRequest build() {
        return deviceListRequest;
    }
}