/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class DeviceAggregateUsageListRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5598833999558811923L;
    private String accountName;
    private List<DeviceId> deviceIds;
    private String endTime;
    private String groupName;
    private String startTime;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("deviceIds")
    public List<DeviceId> getDeviceIds ( ) { 
        return this.deviceIds;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds (List<DeviceId> value) { 
        this.deviceIds = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("endTime")
    public String getEndTime ( ) { 
        return this.endTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("endTime")
    public void setEndTime (String value) { 
        this.endTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("startTime")
    public String getStartTime ( ) { 
        return this.startTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("startTime")
    public void setStartTime (String value) { 
        this.startTime = value;
    }
 
}
 