/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DevicePrlListRequestBuilder {
    //the instance to build
    private DevicePrlListRequest devicePrlListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DevicePrlListRequestBuilder() {
        devicePrlListRequest = new DevicePrlListRequest();
    }

    public DevicePrlListRequestBuilder accountName(String accountName) {
        devicePrlListRequest.setAccountName(accountName);
        return this;
    }

    public DevicePrlListRequestBuilder customFields(List<KvPair> customFields) {
        devicePrlListRequest.setCustomFields(customFields);
        return this;
    }

    public DevicePrlListRequestBuilder deviceIds(List<DeviceId> deviceIds) {
        devicePrlListRequest.setDeviceIds(deviceIds);
        return this;
    }

    public DevicePrlListRequestBuilder groupName(String groupName) {
        devicePrlListRequest.setGroupName(groupName);
        return this;
    }

    public DevicePrlListRequestBuilder servicePlan(String servicePlan) {
        devicePrlListRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DevicePrlListRequest build() {
        return devicePrlListRequest;
    }
}