/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceProvisioningHistoryListResponseBuilder {
    //the instance to build
    private DeviceProvisioningHistoryListResponse deviceProvisioningHistoryListResponse;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceProvisioningHistoryListResponseBuilder() {
        deviceProvisioningHistoryListResponse = new DeviceProvisioningHistoryListResponse();
    }

    public DeviceProvisioningHistoryListResponseBuilder hasMoreData(Boolean hasMoreData) {
        deviceProvisioningHistoryListResponse.setHasMoreData(hasMoreData);
        return this;
    }

    public DeviceProvisioningHistoryListResponseBuilder provisioningHistory(List<ProvisioningHistory> provisioningHistory) {
        deviceProvisioningHistoryListResponse.setProvisioningHistory(provisioningHistory);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceProvisioningHistoryListResponse build() {
        return deviceProvisioningHistoryListResponse;
    }
}