/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class DeviceUsageListRequestBuilder {
    //the instance to build
    private DeviceUsageListRequest deviceUsageListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public DeviceUsageListRequestBuilder() {
        deviceUsageListRequest = new DeviceUsageListRequest();
    }

    public DeviceUsageListRequestBuilder deviceId(DeviceId deviceId) {
        deviceUsageListRequest.setDeviceId(deviceId);
        return this;
    }

    public DeviceUsageListRequestBuilder earliest(String earliest) {
        deviceUsageListRequest.setEarliest(earliest);
        return this;
    }

    public DeviceUsageListRequestBuilder latest(String latest) {
        deviceUsageListRequest.setLatest(latest);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DeviceUsageListRequest build() {
        return deviceUsageListRequest;
    }
}