/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GroupListResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4869572506673270219L;
    private String description;
    private List<DeviceList> devices;
    private Boolean hasMoreData;
    private String name;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devices")
    public List<DeviceList> getDevices ( ) { 
        return this.devices;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devices")
    public void setDevices (List<DeviceList> value) { 
        this.devices = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
}
 