/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class GroupResponseBuilder {
    //the instance to build
    private GroupResponse groupResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GroupResponseBuilder() {
        groupResponse = new GroupResponse();
    }

    public GroupResponseBuilder description(String description) {
        groupResponse.setDescription(description);
        return this;
    }

    public GroupResponseBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        groupResponse.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public GroupResponseBuilder isDefaultGroup(Boolean isDefaultGroup) {
        groupResponse.setIsDefaultGroup(isDefaultGroup);
        return this;
    }

    public GroupResponseBuilder name(String name) {
        groupResponse.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GroupResponse build() {
        return groupResponse;
    }
}