/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class GroupListResponseBuilder {
    //the instance to build
    private GroupListResponse groupListResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GroupListResponseBuilder() {
        groupListResponse = new GroupListResponse();
    }

    public GroupListResponseBuilder description(String description) {
        groupListResponse.setDescription(description);
        return this;
    }

    public GroupListResponseBuilder devices(List<DeviceList> devices) {
        groupListResponse.setDevices(devices);
        return this;
    }

    public GroupListResponseBuilder hasMoreData(Boolean hasMoreData) {
        groupListResponse.setHasMoreData(hasMoreData);
        return this;
    }

    public GroupListResponseBuilder name(String name) {
        groupListResponse.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GroupListResponse build() {
        return groupListResponse;
    }
}