/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class GroupUpdateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5471704904424514940L;
    private List<DeviceId> devicesToAdd;
    private List<DeviceId> devicesToRemove;
    private String newGroupDescription;
    private String newGroupName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devicesToAdd")
    public List<DeviceId> getDevicesToAdd ( ) { 
        return this.devicesToAdd;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devicesToAdd")
    public void setDevicesToAdd (List<DeviceId> value) { 
        this.devicesToAdd = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devicesToRemove")
    public List<DeviceId> getDevicesToRemove ( ) { 
        return this.devicesToRemove;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devicesToRemove")
    public void setDevicesToRemove (List<DeviceId> value) { 
        this.devicesToRemove = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("newGroupDescription")
    public String getNewGroupDescription ( ) { 
        return this.newGroupDescription;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("newGroupDescription")
    public void setNewGroupDescription (String value) { 
        this.newGroupDescription = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("newGroupName")
    public String getNewGroupName ( ) { 
        return this.newGroupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("newGroupName")
    public void setNewGroupName (String value) { 
        this.newGroupName = value;
    }
 
}
 