/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class GroupUpdateRequestBuilder {
    //the instance to build
    private GroupUpdateRequest groupUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public GroupUpdateRequestBuilder() {
        groupUpdateRequest = new GroupUpdateRequest();
    }

    public GroupUpdateRequestBuilder devicesToAdd(List<DeviceId> devicesToAdd) {
        groupUpdateRequest.setDevicesToAdd(devicesToAdd);
        return this;
    }

    public GroupUpdateRequestBuilder devicesToRemove(List<DeviceId> devicesToRemove) {
        groupUpdateRequest.setDevicesToRemove(devicesToRemove);
        return this;
    }

    public GroupUpdateRequestBuilder newGroupDescription(String newGroupDescription) {
        groupUpdateRequest.setNewGroupDescription(newGroupDescription);
        return this;
    }

    public GroupUpdateRequestBuilder newGroupName(String newGroupName) {
        groupUpdateRequest.setNewGroupName(newGroupName);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GroupUpdateRequest build() {
        return groupUpdateRequest;
    }
}