/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class KvPairBuilder {
    //the instance to build
    private KvPair kvPair;

    /**
     * Default constructor to initialize the instance
     */
    public KvPairBuilder() {
        kvPair = new KvPair();
    }

    public KvPairBuilder key(String key) {
        kvPair.setKey(key);
        return this;
    }

    public KvPairBuilder value(String value) {
        kvPair.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public KvPair build() {
        return kvPair;
    }
}