/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LeadInformationResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4731111910696482218L;
    private Boolean hasMoreData;
    private List<LeadResponse> leads;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leads")
    public List<LeadResponse> getLeads ( ) { 
        return this.leads;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leads")
    public void setLeads (List<LeadResponse> value) { 
        this.leads = value;
    }
 
}
 