/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LeadResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5051426118073540068L;
    private Address address;
    private String leadId;
    private String leadState;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("address")
    public Address getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("address")
    public void setAddress (Address value) { 
        this.address = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leadId")
    public String getLeadId ( ) { 
        return this.leadId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leadId")
    public void setLeadId (String value) { 
        this.leadId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("leadState")
    public String getLeadState ( ) { 
        return this.leadState;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("leadState")
    public void setLeadState (String value) { 
        this.leadState = value;
    }
 
}
 