/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class LeadResponseBuilder {
    //the instance to build
    private LeadResponse leadResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LeadResponseBuilder() {
        leadResponse = new LeadResponse();
    }

    public LeadResponseBuilder address(Address address) {
        leadResponse.setAddress(address);
        return this;
    }

    public LeadResponseBuilder leadId(String leadId) {
        leadResponse.setLeadId(leadId);
        return this;
    }

    public LeadResponseBuilder leadState(String leadState) {
        leadResponse.setLeadState(leadState);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LeadResponse build() {
        return leadResponse;
    }
}