/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class LogInResponseBuilder {
    //the instance to build
    private LogInResponse logInResponse;

    /**
     * Default constructor to initialize the instance
     */
    public LogInResponseBuilder() {
        logInResponse = new LogInResponse();
    }

    public LogInResponseBuilder sessionToken(String sessionToken) {
        logInResponse.setSessionToken(sessionToken);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LogInResponse build() {
        return logInResponse;
    }
}