/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class LogInResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5489843119639594061L;
    private String sessionToken;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sessionToken")
    public String getSessionToken ( ) { 
        return this.sessionToken;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sessionToken")
    public void setSessionToken (String value) { 
        this.sessionToken = value;
    }
 
}
 