/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class LogInRequestBuilder {
    //the instance to build
    private LogInRequest logInRequest;

    /**
     * Default constructor to initialize the instance
     */
    public LogInRequestBuilder() {
        logInRequest = new LogInRequest();
    }

    public LogInRequestBuilder username(String username) {
        logInRequest.setUsername(username);
        return this;
    }

    public LogInRequestBuilder password(String password) {
        logInRequest.setPassword(password);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LogInRequest build() {
        return logInRequest;
    }
}