/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class LogOutRequestBuilder {
    //the instance to build
    private LogOutRequest logOutRequest;

    /**
     * Default constructor to initialize the instance
     */
    public LogOutRequestBuilder() {
        logOutRequest = new LogOutRequest();
    }

    public LogOutRequestBuilder sessionToken(String sessionToken) {
        logOutRequest.setSessionToken(sessionToken);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public LogOutRequest build() {
        return logOutRequest;
    }
}