/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class PlaceOfUse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5110990182511369290L;
    private Address address;
    private CustomerName customerName;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("address")
    public Address getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("address")
    public void setAddress (Address value) { 
        this.address = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customerName")
    public CustomerName getCustomerName ( ) { 
        return this.customerName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customerName")
    public void setCustomerName (CustomerName value) { 
        this.customerName = value;
    }
 
}
 