/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ProvisioningHistoryBuilder {
    //the instance to build
    private ProvisioningHistory provisioningHistory;

    /**
     * Default constructor to initialize the instance
     */
    public ProvisioningHistoryBuilder() {
        provisioningHistory = new ProvisioningHistory();
    }

    public ProvisioningHistoryBuilder eventBy(String eventBy) {
        provisioningHistory.setEventBy(eventBy);
        return this;
    }

    public ProvisioningHistoryBuilder eventType(String eventType) {
        provisioningHistory.setEventType(eventType);
        return this;
    }

    public ProvisioningHistoryBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        provisioningHistory.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public ProvisioningHistoryBuilder mdn(String mdn) {
        provisioningHistory.setMdn(mdn);
        return this;
    }

    public ProvisioningHistoryBuilder msisdn(String msisdn) {
        provisioningHistory.setMsisdn(msisdn);
        return this;
    }

    public ProvisioningHistoryBuilder occurredAt(String occurredAt) {
        provisioningHistory.setOccurredAt(occurredAt);
        return this;
    }

    public ProvisioningHistoryBuilder servicePlan(String servicePlan) {
        provisioningHistory.setServicePlan(servicePlan);
        return this;
    }

    public ProvisioningHistoryBuilder status(String status) {
        provisioningHistory.setStatus(status);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProvisioningHistory build() {
        return provisioningHistory;
    }
}