/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ProvisioningHistory 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4862639501745598530L;
    private String eventBy;
    private String eventType;
    private List<KvPair> extendedAttributes;
    private String mdn;
    private String msisdn;
    private String occurredAt;
    private String servicePlan;
    private String status;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("eventBy")
    public String getEventBy ( ) { 
        return this.eventBy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("eventBy")
    public void setEventBy (String value) { 
        this.eventBy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("eventType")
    public String getEventType ( ) { 
        return this.eventType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("eventType")
    public void setEventType (String value) { 
        this.eventType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extendedAttributes")
    public List<KvPair> getExtendedAttributes ( ) { 
        return this.extendedAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes (List<KvPair> value) { 
        this.extendedAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("mdn")
    public String getMdn ( ) { 
        return this.mdn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("mdn")
    public void setMdn (String value) { 
        this.mdn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("msisdn")
    public String getMsisdn ( ) { 
        return this.msisdn;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("msisdn")
    public void setMsisdn (String value) { 
        this.msisdn = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("occurredAt")
    public String getOccurredAt ( ) { 
        return this.occurredAt;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("occurredAt")
    public void setOccurredAt (String value) { 
        this.occurredAt = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
}
 