/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class RegisterCallbackRequestBuilder {
    //the instance to build
    private RegisterCallbackRequest registerCallbackRequest;

    /**
     * Default constructor to initialize the instance
     */
    public RegisterCallbackRequestBuilder() {
        registerCallbackRequest = new RegisterCallbackRequest();
    }

    public RegisterCallbackRequestBuilder name(String name) {
        registerCallbackRequest.setName(name);
        return this;
    }

    public RegisterCallbackRequestBuilder url(String url) {
        registerCallbackRequest.setUrl(url);
        return this;
    }

    public RegisterCallbackRequestBuilder username(String username) {
        registerCallbackRequest.setUsername(username);
        return this;
    }

    public RegisterCallbackRequestBuilder password(String password) {
        registerCallbackRequest.setPassword(password);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RegisterCallbackRequest build() {
        return registerCallbackRequest;
    }
}