/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class RequestResponseBuilder {
    //the instance to build
    private RequestResponse requestResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RequestResponseBuilder() {
        requestResponse = new RequestResponse();
    }

    public RequestResponseBuilder requestId(String requestId) {
        requestResponse.setRequestId(requestId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RequestResponse build() {
        return requestResponse;
    }
}