/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RequestResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4913891619646124217L;
    private String requestId;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("requestId")
    public String getRequestId ( ) { 
        return this.requestId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("requestId")
    public void setRequestId (String value) { 
        this.requestId = value;
    }
 
}
 