/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class RestSuccessResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4643574656253646729L;
    private Boolean success;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("success")
    public Boolean getSuccess ( ) { 
        return this.success;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("success")
    public void setSuccess (Boolean value) { 
        this.success = value;
    }
 
}
 