/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class RestSuccessResponseBuilder {
    //the instance to build
    private RestSuccessResponse restSuccessResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RestSuccessResponseBuilder() {
        restSuccessResponse = new RestSuccessResponse();
    }

    public RestSuccessResponseBuilder success(Boolean success) {
        restSuccessResponse.setSuccess(success);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RestSuccessResponse build() {
        return restSuccessResponse;
    }
}