/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ServicePlanResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4727681979651827581L;
    private String carrierServicePlanCode;
    private String code;
    private List<KvPair> extendedAttributes;
    private String name;
    private Long sizeKb;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("carrierServicePlanCode")
    public String getCarrierServicePlanCode ( ) { 
        return this.carrierServicePlanCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("carrierServicePlanCode")
    public void setCarrierServicePlanCode (String value) { 
        this.carrierServicePlanCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extendedAttributes")
    public List<KvPair> getExtendedAttributes ( ) { 
        return this.extendedAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes (List<KvPair> value) { 
        this.extendedAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sizeKb")
    public Long getSizeKb ( ) { 
        return this.sizeKb;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sizeKb")
    public void setSizeKb (Long value) { 
        this.sizeKb = value;
    }
 
}
 