/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ServicePlanResponseBuilder {
    //the instance to build
    private ServicePlanResponse servicePlanResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ServicePlanResponseBuilder() {
        servicePlanResponse = new ServicePlanResponse();
    }

    public ServicePlanResponseBuilder carrierServicePlanCode(String carrierServicePlanCode) {
        servicePlanResponse.setCarrierServicePlanCode(carrierServicePlanCode);
        return this;
    }

    public ServicePlanResponseBuilder code(String code) {
        servicePlanResponse.setCode(code);
        return this;
    }

    public ServicePlanResponseBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        servicePlanResponse.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public ServicePlanResponseBuilder name(String name) {
        servicePlanResponse.setName(name);
        return this;
    }

    public ServicePlanResponseBuilder sizeKb(Long sizeKb) {
        servicePlanResponse.setSizeKb(sizeKb);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ServicePlanResponse build() {
        return servicePlanResponse;
    }
}