/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ServicePlanUpdateRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4807645235915842651L;
    private String accountName;
    private String currentServicePlan;
    private List<KvPair> customFields;
    private List<DeviceList> devices;
    private String groupName;
    private String servicePlan;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accountName")
    public String getAccountName ( ) { 
        return this.accountName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accountName")
    public void setAccountName (String value) { 
        this.accountName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("currentServicePlan")
    public String getCurrentServicePlan ( ) { 
        return this.currentServicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("currentServicePlan")
    public void setCurrentServicePlan (String value) { 
        this.currentServicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("customFields")
    public List<KvPair> getCustomFields ( ) { 
        return this.customFields;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("customFields")
    public void setCustomFields (List<KvPair> value) { 
        this.customFields = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devices")
    public List<DeviceList> getDevices ( ) { 
        return this.devices;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devices")
    public void setDevices (List<DeviceList> value) { 
        this.devices = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("groupName")
    public String getGroupName ( ) { 
        return this.groupName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("groupName")
    public void setGroupName (String value) { 
        this.groupName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
}
 