/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class ServicePlanUpdateRequestBuilder {
    //the instance to build
    private ServicePlanUpdateRequest servicePlanUpdateRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ServicePlanUpdateRequestBuilder() {
        servicePlanUpdateRequest = new ServicePlanUpdateRequest();
    }

    public ServicePlanUpdateRequestBuilder accountName(String accountName) {
        servicePlanUpdateRequest.setAccountName(accountName);
        return this;
    }

    public ServicePlanUpdateRequestBuilder currentServicePlan(String currentServicePlan) {
        servicePlanUpdateRequest.setCurrentServicePlan(currentServicePlan);
        return this;
    }

    public ServicePlanUpdateRequestBuilder customFields(List<KvPair> customFields) {
        servicePlanUpdateRequest.setCustomFields(customFields);
        return this;
    }

    public ServicePlanUpdateRequestBuilder devices(List<DeviceList> devices) {
        servicePlanUpdateRequest.setDevices(devices);
        return this;
    }

    public ServicePlanUpdateRequestBuilder groupName(String groupName) {
        servicePlanUpdateRequest.setGroupName(groupName);
        return this;
    }

    public ServicePlanUpdateRequestBuilder servicePlan(String servicePlan) {
        servicePlanUpdateRequest.setServicePlan(servicePlan);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ServicePlanUpdateRequest build() {
        return servicePlanUpdateRequest;
    }
}