/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class SessionResetPasswordRequestBuilder {
    //the instance to build
    private SessionResetPasswordRequest sessionResetPasswordRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SessionResetPasswordRequestBuilder() {
        sessionResetPasswordRequest = new SessionResetPasswordRequest();
    }

    public SessionResetPasswordRequestBuilder oldPassword(String oldPassword) {
        sessionResetPasswordRequest.setOldPassword(oldPassword);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SessionResetPasswordRequest build() {
        return sessionResetPasswordRequest;
    }
}