/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SessionResetPasswordResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4640655155043728082L;
    private String newPassword;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("newPassword")
    public String getNewPassword ( ) { 
        return this.newPassword;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("newPassword")
    public void setNewPassword (String value) { 
        this.newPassword = value;
    }
 
}
 