/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SessionResetPasswordRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5616926185661744622L;
    private String oldPassword;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("oldPassword")
    public String getOldPassword ( ) { 
        return this.oldPassword;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("oldPassword")
    public void setOldPassword (String value) { 
        this.oldPassword = value;
    }
 
}
 