/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class SmsMessageBuilder {
    //the instance to build
    private SmsMessage smsMessage;

    /**
     * Default constructor to initialize the instance
     */
    public SmsMessageBuilder() {
        smsMessage = new SmsMessage();
    }

    public SmsMessageBuilder deviceIds(List<DeviceId> deviceIds) {
        smsMessage.setDeviceIds(deviceIds);
        return this;
    }

    public SmsMessageBuilder message(String message) {
        smsMessage.setMessage(message);
        return this;
    }

    public SmsMessageBuilder timestamp(String timestamp) {
        smsMessage.setTimestamp(timestamp);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SmsMessage build() {
        return smsMessage;
    }
}