/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class SmsMessagesResponseBuilder {
    //the instance to build
    private SmsMessagesResponse smsMessagesResponse;

    /**
     * Default constructor to initialize the instance
     */
    public SmsMessagesResponseBuilder() {
        smsMessagesResponse = new SmsMessagesResponse();
    }

    public SmsMessagesResponseBuilder hasMoreData(Boolean hasMoreData) {
        smsMessagesResponse.setHasMoreData(hasMoreData);
        return this;
    }

    public SmsMessagesResponseBuilder messages(List<SmsMessage> messages) {
        smsMessagesResponse.setMessages(messages);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SmsMessagesResponse build() {
        return smsMessagesResponse;
    }
}