/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class SmsMessagesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5021985838526517916L;
    private Boolean hasMoreData;
    private List<SmsMessage> messages;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("hasMoreData")
    public Boolean getHasMoreData ( ) { 
        return this.hasMoreData;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData (Boolean value) { 
        this.hasMoreData = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("messages")
    public List<SmsMessage> getMessages ( ) { 
        return this.messages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("messages")
    public void setMessages (List<SmsMessage> value) { 
        this.messages = value;
    }
 
}
 