/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class SMSSendRequestBuilder {
    //the instance to build
    private SMSSendRequest sMSSendRequest;

    /**
     * Default constructor to initialize the instance
     */
    public SMSSendRequestBuilder() {
        sMSSendRequest = new SMSSendRequest();
    }

    public SMSSendRequestBuilder accountName(String accountName) {
        sMSSendRequest.setAccountName(accountName);
        return this;
    }

    public SMSSendRequestBuilder customFields(List<KvPair> customFields) {
        sMSSendRequest.setCustomFields(customFields);
        return this;
    }

    public SMSSendRequestBuilder dataEncoding(String dataEncoding) {
        sMSSendRequest.setDataEncoding(dataEncoding);
        return this;
    }

    public SMSSendRequestBuilder deviceIds(List<DeviceId> deviceIds) {
        sMSSendRequest.setDeviceIds(deviceIds);
        return this;
    }

    public SMSSendRequestBuilder groupName(String groupName) {
        sMSSendRequest.setGroupName(groupName);
        return this;
    }

    public SMSSendRequestBuilder servicePlan(String servicePlan) {
        sMSSendRequest.setServicePlan(servicePlan);
        return this;
    }

    public SMSSendRequestBuilder smsMessage(String smsMessage) {
        sMSSendRequest.setSmsMessage(smsMessage);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SMSSendRequest build() {
        return sMSSendRequest;
    }
}