/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Usage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4841635157673161711L;
    private Long bytesUsed;
    private List<KvPair> extendedAttributes;
    private String servicePlan;
    private Integer smsUsed;
    private String source;
    private String timestamp;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("bytesUsed")
    public Long getBytesUsed ( ) { 
        return this.bytesUsed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("bytesUsed")
    public void setBytesUsed (Long value) { 
        this.bytesUsed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("extendedAttributes")
    public List<KvPair> getExtendedAttributes ( ) { 
        return this.extendedAttributes;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes (List<KvPair> value) { 
        this.extendedAttributes = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("servicePlan")
    public String getServicePlan ( ) { 
        return this.servicePlan;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("servicePlan")
    public void setServicePlan (String value) { 
        this.servicePlan = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("smsUsed")
    public Integer getSmsUsed ( ) { 
        return this.smsUsed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("smsUsed")
    public void setSmsUsed (Integer value) { 
        this.smsUsed = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("source")
    public String getSource ( ) { 
        return this.source;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("source")
    public void setSource (String value) { 
        this.source = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("timestamp")
    public String getTimestamp ( ) { 
        return this.timestamp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("timestamp")
    public void setTimestamp (String value) { 
        this.timestamp = value;
    }
 
}
 