/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.models;

import java.util.*;

public class UsageBuilder {
    //the instance to build
    private Usage usage;

    /**
     * Default constructor to initialize the instance
     */
    public UsageBuilder() {
        usage = new Usage();
    }

    public UsageBuilder bytesUsed(Long bytesUsed) {
        usage.setBytesUsed(bytesUsed);
        return this;
    }

    public UsageBuilder extendedAttributes(List<KvPair> extendedAttributes) {
        usage.setExtendedAttributes(extendedAttributes);
        return this;
    }

    public UsageBuilder servicePlan(String servicePlan) {
        usage.setServicePlan(servicePlan);
        return this;
    }

    public UsageBuilder smsUsed(Integer smsUsed) {
        usage.setSmsUsed(smsUsed);
        return this;
    }

    public UsageBuilder source(String source) {
        usage.setSource(source);
        return this;
    }

    public UsageBuilder timestamp(String timestamp) {
        usage.setTimestamp(timestamp);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Usage build() {
        return usage;
    }
}