/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://example.com/api/m2m/v1";

    //TODO: Replace the apiKey with an appropriate value
    public static String apiKey = "";

}
