/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */
package com.example.exceptions;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.example.http.client.HttpContext;

public class RestErrorResponseException 
        extends APIException
        implements java.io.Serializable {
    private static final long serialVersionUID = 5074480007115834278L;
    private String errorCode;
    private String errorMessage;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("errorCode")
    public String getErrorCode ( ) { 
        return this.errorCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("errorCode")
    private void setErrorCode (String value) { 
        this.errorCode = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("errorMessage")
    public String getErrorMessage ( ) { 
        return this.errorMessage;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("errorMessage")
    private void setErrorMessage (String value) { 
        this.errorMessage = value;
    }
 
    /**
     * Initialization constructor
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public RestErrorResponseException(String reason, HttpContext context) {
        super(reason, context);
    }
}
 